import Head from "next/head";
import HomePage from "../Containers/Home/HomePage";

export default function Home({ props }) {
  return (
    <div>
      <Head>
        <title>Typiano</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage {...props} />
    </div>
  );
}
