import Head from "next/head";
import Type from "../components/Type";

const data = ["1", "A", "m", " ", "4", "5", "/", "*"];

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center items-center min-h-screen">
        <Type data={data} />
      </div>
    </div>
  );
}
